services:
  - type: worker
    env: node
    name: basic-starter
    buildCommand: "npm install && npm run build"
    startCommand: "node dist/index.js"
    autoDeploy: false
    plan: starter
    envVars:
      - key: TRIGGER_API_KEY
        sync: false